### ISSUE TITLE
lore server &

### ISSUE THREAD

**Issue by mullerhai** [instacart/lore#101]
all thing is  ok  ,but when  I try to  exec  lore server  in  centos 7  terminal console

meet error
console output 
root@medell lasa]# lore  server 
Traceback (most recent call last):
  File "/usr/local/python3/bin/lore", line 11, in <module>
    sys.exit(main())
  File "/usr/local/python3/lib/python3.6/site-packages/lore/__main__.py", line 352, in main
    known.func(known, unknown)
  File "/usr/local/python3/lib/python3.6/site-packages/lore/__main__.py", line 530, in server
    os.execv(env.BIN_FLASK, args)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by mullerhai** [comment]
have solved ,beauce of  the pyenv  of  project has not install  flask 0.12.4 ,just wrtite one  line in Project root  directory  requirements.txt  [flask==0.12.4]

**Comment by montanalow** [comment]
Thanks for the report! I have added the proper dependency in 0.6.14.

https://github.com/instacart/lore/commit/68809d054af388a57ae844870dd17439e41aa714
