### ISSUE TITLE
zipimport.ZipImportError: can't decompress data; zlib not available

### ISSUE THREAD

**Issue by thu4nvd** [instacart/lore#102]
I run this command after install lore:
```
$ lore init my_app --python-version=3.6.4 --keras --xgboost --postgres
```
It returns result as below:
```
BUILD FAILED (Debian 9.4 using python-build 1.2.6)

Inspect or clean up the working tree at /tmp/python-build.20180726150343.2385
Results logged to /tmp/python-build.20180726150343.2385.log

Last 10 log lines:
    sys.exit(ensurepip._main())
  File "/tmp/python-build.20180726150343.2385/Python-3.6.4/Lib/ensurepip/__init__.py", line 204, in _main
    default_pip=args.default_pip,
  File "/tmp/python-build.20180726150343.2385/Python-3.6.4/Lib/ensurepip/__init__.py", line 117, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/tmp/python-build.20180726150343.2385/Python-3.6.4/Lib/ensurepip/__init__.py", line 27, in _run_pip
    import pip
zipimport.ZipImportError: can't decompress data; zlib not available
Makefile:1099: recipe for target 'install' failed
make: *** [install] Error 1
Traceback (most recent call last):
  File "/usr/local/bin/lore", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/lore/__main__.py", line 352, in main
    known.func(known, unknown)
  File "/usr/local/lib/python3.5/dist-packages/lore/__main__.py", line 608, in init
    install(parsed, unknown)
  File "/usr/local/lib/python3.5/dist-packages/lore/__main__.py", line 625, in install
    install_python_version()
  File "/usr/local/lib/python3.5/dist-packages/lore/__main__.py", line 1039, in install_python_version
    subprocess.check_call((env.BIN_PYENV, 'install', env.PYTHON_VERSION))
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('/home/thuan/.pyenv/bin/pyenv', 'install', '3.6.4')' returned non-zero exit status 1
```
My system info:  ( refer issue #99 for my system info)
OS: Debian 9.4 stretch
Kernel: x86_64 Linux 4.9.0-6-amd64

**Comment by montanalow** [comment]
For debian, I believe you may need to `yum install zlib-devel`

There are other suggested fixes here:
https://unix.stackexchange.com/questions/291737/zipimport-zipimporterror-cant-decompress-data-zlib-not-available

Please let me know what works for you, it would be great if we could detect and correct this missing system dependency automatically.

**Comment by thu4nvd** [comment]
I noticed that I have to satisfy the pyenv first.
This command to install requirements packages on debian 9 to solve the issues, thanks again for the advice.
```
sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev
```
Link: https://github.com/pyenv/pyenv/wiki
