### ISSUE TITLE
librato.exceptions.Unauthorized when using `lore api`

### ISSUE THREAD

**Issue by Guzzii** [instacart/lore#169]
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/app/.heroku/python/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/librato/aggregator.py", line 191, in submit
    query_props=self.to_payload())
  File "/app/.heroku/python/lib/python3.6/site-packages/librato/__init__.py", line 209, in _mexe
    resp_data, success, backoff = self._process_response(resp, backoff)
  File "/app/.heroku/python/lib/python3.6/site-packages/librato/__init__.py", line 183, in _process_response
    raise exceptions.get(resp.status, resp_data)
librato.exceptions.Unauthorized: [401] Credentials are required to access this resource.
10:56:55.911  WARNING  threading:120 => Exception in thread Thread-3:
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/app/.heroku/python/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/librato/aggregator.py", line 191, in submit
    query_props=self.to_payload())
  File "/app/.heroku/python/lib/python3.6/site-packages/librato/__init__.py", line 209, in _mexe
    resp_data, success, backoff = self._process_response(resp, backoff)
  File "/app/.heroku/python/lib/python3.6/site-packages/librato/__init__.py", line 183, in _process_response
    raise exceptions.get(resp.status, resp_data)
librato.exceptions.Unauthorized: [401] Credentials are required to access this resource.
```

**Comment by ganesh-krishnan** [comment]
We should get rid of `librato` inside of `lore`, but a quick fix is to ensure that `LIBRATO_USER` is not set in your environment.
