### ISSUE TITLE
Lore assumes pyenv is installed in a specific way

### ISSUE THREAD

**Issue by thomasfulton** [instacart/lore#170]
Specifically it assumes it is NOT installed through brew, but manually installed by cloning the git repo. If you try to run `lore install` with pyenv installed this way you get

```
> lore install                                                                                                                                                                                   
WARNING pyenv executable is not present at /Users/thomasfulton/.pyenv/bin/pyenv
Would you like to blow away ~/.pyenv and rebuild from scratch? [Y/n] n
ERROR please fix pyenv before continuing
```

If you symlink your pyenv executable to that location you eventually get

```
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/Users/thomasfulton/.pyenv/versions/3.7.2/bin/lore", line 11, in <module>
    sys.exit(main())
  File "/Users/thomasfulton/.pyenv/versions/3.7.2/lib/python3.7/site-packages/lore/__main__.py", line 355, in main
    known.func(known, unknown)
  File "/Users/thomasfulton/.pyenv/versions/3.7.2/lib/python3.7/site-packages/lore/__main__.py", line 652, in install
    install_python_version()
  File "/Users/thomasfulton/.pyenv/versions/3.7.2/lib/python3.7/site-packages/lore/__main__.py", line 1098, in install_python_version
    subprocess.check_call(('git', '-C', env.PYENV, 'pull'))
  File "/Users/thomasfulton/.pyenv/versions/3.7.2/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('git', '-C', '/Users/thomasfulton/.pyenv', 'pull')' returned non-zero exit status 128.
```

**Comment by metatron1973** [comment]
System is still racked with fraud from within need a full forensic audit of entire instacart system ![image](https://user-images.githubusercontent.com/80199202/179419602-1c2da968-8720-4610-b6b2-b1493eb9f5bd.png)
