### ISSUE TITLE
ERROR: unit.test_subscribers (unittest.loader._FailedTest)

### ISSUE THREAD

**Issue by Betty1999Kamanthe** [instacart/lore#177]
ERROR: unit.test_subscribers (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: unit.test_subscribers
Traceback (most recent call last):
  File "/home/betty/.pyenv/versions/3.7.9/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/betty/.pyenv/versions/3.7.9/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/betty/my_app/tests/unit/test_subscribers.py", line 4, in <module>
    from my_app.models.subscribers import DeepName, BoostedName
  File "/home/betty/my_app/my_app/models/subscribers.py", line 2, in <module>
    import lore.models.keras
  File "/home/betty/.pyenv/versions/3.7.9/envs/my_app/lib/python3.7/site-packages/lore/models/__init__.py", line 1, in <module>
    from lore.models import base
  File "/home/betty/.pyenv/versions/3.7.9/envs/my_app/lib/python3.7/site-packages/lore/models/base.py", line 11, in <module>
    import botocore
ModuleNotFoundError: No module named 'botocore'

----------------------------------------------------------------------
Ran 1 test in 0.092s

FAILED (errors=1)

**Comment by metatron1973** [comment]
Huge issues with every aspect of instacart system people are messing with driver ratings and tips and the fraud must be removed immediately....

**Comment by metatron1973** [comment]
Daily fraud within the system ![image](https://user-images.githubusercontent.com/80199202/177382043-e5a1a8e5-2677-4233-a845-59468e9d6a7e.png)

**Comment by metatron1973** [comment]
Still complete fraud across the board violating SEC laws with securities fraud ![image](https://user-images.githubusercontent.com/80199202/184705580-84c5f943-b247-43a6-8b55-39b17894109c.png)

**Comment by metatron1973** [comment]
This has to be turned over to justice Dept and SEC as fraud ...https://www.reddit.com/r/InstacartShoppers/comments/mtcgxd/tips_are_being_stolen_by_instacart_in_some_cases/
![image](https://user-images.githubusercontent.com/80199202/185218044-10cdb91b-6b94-4e69-9609-d90a36ee19b8.png)

**Comment by metatron1973** [comment]
Indra cart is fraudulent stealing tips from hard workers ![image](https://user-images.githubusercontent.com/80199202/202924733-7050fb74-d48d-421d-8667-97ffffa375ec.png)

**Comment by metatron1973** [comment]
Complete fraud inside Instacart stating system ![image](https://user-images.githubusercontent.com/80199202/204348280-1c13c816-0247-41bf-a9e5-21de6bab8e62.png)
