### ISSUE TITLE
Unsupported Locale Setting on Windows

### ISSUE THREAD

**Issue by brinew27** [instacart/lore#75]
Hi there,

When I install Lore and try to create a test app using the code listed in the blog post:

```
lore init my_app --python-version=3.6.4 --keras
```

I get the following stack trace:

```
Traceback (most recent call last):
  File "c:\users\brian\anaconda2\envs\lore\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\brian\anaconda2\envs\lore\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\brian\Anaconda2\envs\Lore\Scripts\lore.exe\__main__.py", line 5, in <module>
  File "c:\users\brian\anaconda2\envs\lore\lib\site-packages\lore\__init__.py", line 7, in <module>
    from lore import env, util, ansi
  File "c:\users\brian\anaconda2\envs\lore\lib\site-packages\lore\env.py", line 52, in <module>
    locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')
  File "c:\users\brian\anaconda2\envs\lore\lib\locale.py", line 598, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

I tried Googling around a bit for this issue but couldn't find a good resolution.

Thanks!

Brian

**Comment by oltip** [comment]
I have the same problem. Wasted all day searching for solutions online, but nothing. Anybody could help?

**Comment by montanalow** [comment]
I will take a look on my windows machine when I get home. pyenv does not support windows, and is how Lore manages dependencies, so this may be tricky to get around.

**Comment by montanalow** [comment]
@oltip sorry about the delete, your comment was showing twice and I was trying to clean up the thread. It has been noted as a +1.

**Comment by brinew27** [comment]
Just as an FYI, after doing my own Googling, I say that this was a way to get around this was to adjust:

```
File "c:\users\brian\anaconda2\envs\lore\lib\site-packages\lore\env.py", line 52, in <module>
    locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')
```

to

```
        locale.setlocale(locale.LC_ALL, 'English_United States.1252')
```

This seems to have resolved the issue for now.

**Comment by montanalow** [comment]
@brinew27 can you help test this patch on your system? My box is Windows 10.

1) `pip install -e git+https://github.com/instacart/lore@montana/windows`
2) `lore init`...
3) replace `lore==...` with `-e git+https://github.com/instacart/lore@montana/windows` in `requirements.txt` in your project directory.
4) `lore install`

Then you should be good to continue with demo
